POST http://localhost:8080/realms/acme/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

grant_type=client_credentials
&client_id=sa-acme-pix-worker
&client_secret=YVSRYeUp0GAyjE11e1KT9rkkyZ5vPZiJ
&scope=acme-pix-api:reader